use Academy;

CREATE TABLE Teachers
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(MAX) NOT NULL,
    [Surname] NVARCHAR(MAX) NOT NULL
);

CREATE TABLE Curators
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [TeacherID] INT FOREIGN KEY REFERENCES Teachers(ID)
);

CREATE TABLE Deans
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [TeacherID] INT FOREIGN KEY REFERENCES Teachers(ID)
);

CREATE TABLE Assistants
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [TeacherID] INT FOREIGN KEY REFERENCES Teachers(ID)
);

CREATE TABLE Faculties
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Building] INT CHECK ([Building] BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL,
    [FacultyID] INT FOREIGN KEY REFERENCES Deans(ID)
);

CREATE TABLE Heads
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [TeacherID] INT FOREIGN KEY REFERENCES Teachers(ID)
);

CREATE TABLE Departments
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Building] INT CHECK ([Building] BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL,
    [FacultyID] INT FOREIGN KEY REFERENCES Faculties(ID),
    [HeadID] INT FOREIGN KEY REFERENCES Heads(ID)
);

CREATE TABLE Groups
(
    ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(10) UNIQUE NOT NULL,
    [Year] INT CHECK ([Year] BETWEEN 1 AND 5) NOT NULL,
    [DepartmentID] INT FOREIGN KEY REFERENCES Departments(ID)
);

CREATE TABLE GroupsCurators
(
    ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
    [CuratorID] INT FOREIGN KEY REFERENCES Curators(ID),
    [GroupID] INT FOREIGN KEY REFERENCES Groups(ID)
);

CREATE TABLE Subjects
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Name] NVARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE LectureRooms
(
    ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
    [Building] INT CHECK ([Building] BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE Lectures
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [SubjectID] INT FOREIGN KEY REFERENCES Subjects(ID),
    [TeacherID] INT FOREIGN KEY REFERENCES Teachers(ID)
);

CREATE TABLE GroupsLectures
(
    ID INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
    [GroupID] INT FOREIGN KEY REFERENCES Groups(ID),
    [LectureID] INT FOREIGN KEY REFERENCES Lectures(ID)
);

CREATE TABLE LectureRooms
(
    ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    [Building] INT CHECK ([Building] BETWEEN 1 AND 5) NOT NULL,
    [Name] NVARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE Schedules
(
  ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
  Class INT CHECK (Class BETWEEN 1 AND 8) NOT NULL,
  DayOfWeek INT CHECK (DayOfWeek BETWEEN 1 AND 7) NOT NULL,
  Week INT CHECK (Week BETWEEN 1 AND 52) NOT NULL,
  LectureID INT FOREIGN KEY REFERENCES Lectures(ID),
  LectureRoomID INT NOT NULL FOREIGN KEY REFERENCES LectureRooms(ID)
);



--1
SELECT Name FROM LectureRooms
INNER JOIN Schedules ON Schedules.ID = Schedules.LectureRoomID
INNER JOIN Lectures ON Lectures.ID = Lectures.ID
INNER JOIN Teachers ON Lectures.TeacherID = Teachers.ID
WHERE (Teachers.Name = N'Edward' AND Teachers.Surname = N'Hopper')